"""Add nullable current_trip_status and current_trip_id to User model

Revision ID: 07ebc10b6520
Revises: 627162a3b056
Create Date: 2025-09-01 12:27:09.135648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ebc10b6520'
down_revision = '627162a3b056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_trip_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_trip_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_trip_id')
        batch_op.drop_column('current_trip_status')

    # ### end Alembic commands ###
