"""Add location to User model

Revision ID: 966313f57173
Revises: d12397fe3349
Create Date: 2025-08-30 17:03:55.791081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966313f57173'
down_revision = 'd12397fe3349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
